[package]
name = "garden_hell"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_xpbd_3d = "0.4.2"
bevy-inspector-egui = "0.23.4"
bevy_asset_loader = {version = "0.20.0", features = ["standard_dynamic_assets", "3d"]}
leafwing-input-manager = "0.13.0"

